CREATE TABLE `place` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `img` varchar(128) DEFAULT NULL,
  `text` varchar(1024) DEFAULT NULL,
  `lat` float DEFAULT NULL,
  `lon` float DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `sure`.`place`
(`id`,
`name`,
`img`,
`text`,
`lat`,
`lon`)
VALUES
(1,
'Althofblock',
'http://10.0.2.2/img/sure/althoffblock.jpeg',
'Der Althoffblock ist eine staedtische Wohnanlage in Dortmund, mit deren Bau 1914 begonnen wurde. Die Genossenschaft Spar- und Bauverein Dortmund eG, die hier gegruendet wurde, haelt in Dortmund 2007 etwa 12.000 Wohnungen, davon etwa 1600 im Wohnquartier Althoffblock.',
51.5055567990323, 7.444003056836296
),
(2,
'Schloss Bladenhorst',
'http://10.0.2.2/img/sure/bladenhorst.jfif',
'Schloss Bladenhorst ist ein Wasserschloss im Stadtteil Bladenhorst der Stadt Castrop-Rauxel.',
51.569595,
7.279296
),
(3,
'Castrop-Rauxel Hauptbahnhof',
'http://10.0.2.2/img/sure/castrop_hbf.jfif',
'Der Bahnhof Castrop-Rauxel Hauptbahnhof liegt im Ortskern des Castrop-Rauxeler Stadtteils Rauxel. Er ist neben Recklinghausen Hauptbahnhof der einzige als Hauptbahnhof bezeichnete Bahnhof im Kreis Recklinghausen.',
51.573279, 7.304929
),
(4,
'Borsigplatz ConcordiArt Cafe',
'http://10.0.2.2/img/sure/borsigplatz_concordia.jpeg',
'Der Borsigplatz in Dortmund liegt nordoestlich der Innenstadt im oestlichen Bereich der Dortmunder Nordstadt. Der Borsigplatz ist eine kreisfoermige Verkehrsfuehrung mit sechs sternfoermig angeordneten Zufahrtsstraßen.',
51.523667, 7.481968
),
(5,
'Corsopassage',
'http://10.0.2.2/img/sure/corsopassage.jpg',
'Der Westenhellweg ist ein Teil der zentralen Einkaufsstraße in der Dortmunder Innenstadt. Er liegt gegenueber der Kampstraße, welche zurzeit zu einer Flaniermeile umgebaut wird.',
51.514665, 7.464373
),
(6,
'Dortmund Hauptbahnhof',
'http://10.0.2.2/img/sure/dortmund_hbf.jpg',
'Der Hauptbahnhof Dortmund ist der bedeutendste Bahnhof der Stadt Dortmund und steht mit taeglich rund 130.000 Reisenden auf Platz 14 der meistfrequentierten Fernbahnhoefe der Deutschen Bahn',
51.516946, 7.459637
),
(7,
'Altes Stadthaus',
'http://10.0.2.2/img/sure/dortmund_stadtthaus.jpg',
'Das Alte Stadthaus der Stadt Dortmund wurde 1899 nach Entwurf von Stadtbaurat Friedrich Kullrich im Stil der Neurenaissance errichtet. Nach starker Beschaedigung im Zweiten Weltkrieg wurde es wieder aufgebaut, jedoch in leicht vereinfachter Form. ',
51.510974, 7.467046
),
(8,
'Emscherunterfuehrung',
'http://10.0.2.2/img/sure/emscher.jfif',
'Auf 9,7 Kilometern durchquert die Emscher Castrop-Rauxel und hat die noerdlichen Stadtteile nachhaltig in der Entwicklung gepraegt. Die einst wilde Emscher wurde Anfang des 20. Jahrhunderts begradigt. Aus der "schwarzen" Emscher der Industriealisierung soll die "Blaue Emscher" mit Wohnqalitaet und Freizeitcharakter werden.',
51.594994, 7.296762
),
(9,
'Essen Fronhausen',
'http://10.0.2.2/img/sure/essen_fronhausen.jpg',
'Frohnhausen ist ein Stadtteil im Westen der Stadt Essen.',
51.448252, 6.967029
),
(10,
'Zeche Erin',
'http://10.0.2.2/img/sure/erin.jpg',
'Die Zeche Erin war ein Steinkohle-Bergwerk in Castrop-Rauxel.',
51.546489, 7.305033
),
(11,
'Frankfurt',
'http://10.0.2.2/img/sure/frankfurt.jfif',
'Das Drogen-Elend im Frankfurter Bahnhofsviertel ist waehrend der Corona-Pandemie groeßer geworden. Die Stadtregierung will mit neuen Modellprojekten unter anderem fuer schwerst Crack-Abhaengige gegensteuern.',
50.108390, 8.666121
),
(12,
'Frankfurt Hauptbahnhof',
'http://10.0.2.2/img/sure/frankfurt_hbf.jfif',
'Frankfurt (Main) Hauptbahnhof ist der groeßte Bahnhof in Frankfurt am Main. Mit taeglich etwa 493.000 Reisenden ist er nach dem Hamburger Hauptbahnhof der am zweitstaerksten frequentierte Fernbahnhof in Deutschland. ',
50.107372, 8.664383
),
(13,
'Gloertalsperre',
'http://10.0.2.2/img/sure/gloertalsperre.jfif',
'Die Gloertalsperre ist eine kleine Talsperre auf der Grenze des Ennepe-Ruhr-Kreises und des Maerkischen Kreises in Nordrhein-Westfalen, Deutschland. ',
51.242919, 7.500999
),
(14,
'Hansaplatz Arkaden',
'http://10.0.2.2/img/sure/hansaplatz_arkaden.jpg',
'Der Hansaplatz ist heute Standort des Dortmunder Wochenmarktes. Neben dieser Nutzung finden auf dem Platz auch haeufig Großveranstaltungen und politische Kundgebungen statt.',
51.513200, 7.465010
),
(15,
'Hansaplatz Arkaden 2',
'http://10.0.2.2/img/sure/hansaplatz_arkaden-2.jpg',
'Der Hansaplatz ist ein zentraler Platz in der Dortmunder Innenstadt. Der Platz liegt suedwestlich des Alten Marktes und wurde ab 1904 in mehreren Phasen angelegt.',
51.512561, 7.464071
),
(16,
'Hohensyburg Ruine',
'http://10.0.2.2/img/sure/hohensyburg.jfif',
'Die Hohensyburg, auch Syburg genannt, ist die Ruine einer Hoehenburg auf dem rund 245 m ue. NN hohen Syberg oberhalb des Zusammenflusses von Ruhr und Lenne in den kuenstlich angelegten Hengsteysee im suedlichen Dortmunder Stadtteil Syburg. ',
51.420034, 7.486934
),
(17,
'Koernerplatz',
'http://10.0.2.2/img/sure/koernerplatz.jpg',
'In den ersten Plaenen sollte lediglich ein einfacher innerstaedtischer Platz geschaffen werden, der schließlich auf Intervention der Bezirksvertretung Innenstadt-Ost einerseits eingepfostet, andererseits aber auch durch Baumanpflanzungen eine Aufenthaltsqualitaet erhalten sollte.',
51.512759, 7.502927
),
(18,
'Kreuzung Hansa- Kampstraße',
'http://10.0.2.2/img/sure/kreuzung_hansastr_kampstr.jpg',
'Dortmund Innenstadt, Polizeieinsatz',
51.515028, 7.464114
),
(19,
'Die Kurbel',
'http://10.0.2.2/img/sure/kurbel.jfif',
'Kino der Stadt Castrop-Rauxel, ab ca. 1963 erhielt es den Namen "Kurbel". Anfang der 90er kam das kleine "Filmstudio" als zweiter Saal dazu. Das Kino wurde nicht mehr digitalisiert und schloss Ende 2014 die Pforten',
51.550771, 7.310074
),
(20,
'Muensterplatz',
'http://10.0.2.2/img/sure/muensterplatz.jpg',
'Das Dorf Castrop hatte zwar seit 1484 Marktrechte inne – aber keinen Marktplatz. Die Maerkte fanden in verschiedenen breiteren Straßen statt. Als der Ire William Thomas Mulvany ab 1866 die Zeche Erin aufbaute, vermehrte sich die Einwohnerzahl Castrops rasch, sodass sich das Marktgeschehen ausweitete und der Marktplatz in seiner heutigen Form entstand.',
51.547872, 7.311303
),
(21,
'Phoenix West',
'http://10.0.2.2/img/sure/phoenix_west.jpeg',
'Die Hoerder Bergwerks- und Huetten-Verein, kurz Hoerder Verein, ist ein ehemaliges Montanunternehmen in Dortmund.',
51.492170, 7.511555
),
(22,
'Propsteikirche',
'http://10.0.2.2/img/sure/propsteikriche.jpg',
'Die Propsteikirche St. Johannes Baptist ist eine der vier innerstaedtischen Kirchen Dortmunds. Die Kirche liegt suedlich des Westenhellwegs und westlich des Hansaplatzes. Sie ist die einzige roemisch-katholische Kirche innerhalb des Dortmunder Wallrings.',
51.513752, 7.462889
),
(23,
'Reinoldikirche',
'http://10.0.2.2/img/sure/reinoldikirche.jpg',
'St. Reinoldi, auch Reinoldikirche, ist eine evangelische Kirche in der Dortmunder Innenstadt. Sie ist ihrem Gruendungsdatum nach die aelteste erhaltene Kirche im historischen Stadtzentrum.',
51.514709, 7.466994
),
(24,
'Rheinischestraße',
'http://10.0.2.2/img/sure/rheinischestr.jpg',
'Lange Zeit war die Gegend um das Dortmunder U und entlang der Rheinischen Straße durch den Strukturwandel von Leerstand und sozialen Verwerfungen gepraegt. Mittlerweile fuellen sich Leerstaende mit neuen Angeboten und das Areal erfreut sich auch als Wohnquartier fuer Kuenstler, Kreative und Studenten einer steigenden Nachfrage und einer multikulturellen Bevoelkerung.',
51.51354285780233, 7.452128208493843
),
(25,
'So-Da-Bruecke',
'http://10.0.2.2/img/sure/soda.jfif',
'So-da-Bruecke, Soda-Bruecke oder Geisterbruecke ist eine innerhalb Deutschlands gebraeuchliche umgangssprachliche Bezeichnung fuer eine Bruecke, die einfach nur „so da“ ist, also derzeit keinerlei Funktion erfuellt und mangels Zufahrten nicht benutzbar ist.',
51.537428, 7.339085),
(26,
'Stadttheater',
'http://10.0.2.2/img/sure/stadttheater.jpg',
'Das Theater Dortmund hat seinen Ursprung im Jahr 1904 und ist mit ueber 500 Mitarbeitern eines der groeßten Theater Deutschlands (Stand 2010). Das Theater gliedert sich in die sechs Sparten Konzerte, Musiktheater, Schauspiel, Ballett, Kinder- und Jugendtheater und der Akademie fuer Theater und Digitalitaet, welche jeweils unter eigener kuenstlerischer Leitung stehen.',
51.511243, 7.461002),
(27,
'Loewenhof Stahlhaus',
'http://10.0.2.2/img/sure/stahlhaus.jpg',
'Der Loewenhof ist ein Gebaeude in der Innenstadt von Dortmund. Er beherbergte im Laufe seiner Geschichte eines der groeßten Konzert-Cafés Westdeutschlands, war Firmensitz der Heinrich August Schulte Eisenhandlung und ist heute Sitz der Volkshochschule Dortmund.',
51.517295, 7.463219),
(28,
'Loewenhof Stahlhaus',
'http://10.0.2.2/img/sure/tuffi.jfif',
'Tuffi (* 1946 in Indien; † 1989 in Paris) war eine asiatische Elefantenkuh des Zirkus Althoff, die am 21. Juli 1950 im Alter von vier Jahren in Wuppertal aus der fahrenden Schwebebahn in die Wupper sprang.',
51.268568, 7.193653),
(29,
'Dortmunder U',
'http://10.0.2.2/img/sure/u.png',
'Das Dortmunder U, auch U-Turm genannt, ist ein 1926/1927 als „Gaer- und Lagerkeller“ der Dortmunder Union Brauerei errichtetes Hochhaus am westlichen Rand der Dortmunder City.',
51.5148232249795, 7.453496624538426),
(30,
'Volkswohl-Bund Versicherungen',
'http://10.0.2.2/img/sure/vb.jfif',
'Die Volkswohl Bund Versicherungen sind ein 1919 gegruendetes Versicherungsunternehmen, das in Dortmund ansaessig ist und sich auf den Maklervertrieb spezialisiert hat.',
51.509781, 7.462613),
(31,
'Westfalenpark',
'http://10.0.2.2/img/sure/westfalenpark.jpg',
'Großer Park mit Rosengarten, Minizug, Turm mit Aussichtsplattform und Café sowie Open-Air-Veranstaltungen.',
51.49477395230557, 7.477382469868732),
(32,
'Zeche Victor 3/4',
'http://10.0.2.2/img/sure/zeche_victor.jpg',
'Die Zeche Victor war ein Steinkohlen-Bergwerk in Castrop-Rauxel im Ruhrgebiet. Die neue Kokerei auf Schacht 3/4 ging 1948 in Betrieb. Die Foerderung erreichte bald 1,3 Millionen Tonnen Kohle jaehrlich bei 5.600 Beschaeftigten.',
51.586098, 7.328721),
(33,
'Zeche Victoria Mathias',
'http://10.0.2.2/img/sure/zeche_Victoria_mathias.jpg',
'Die Zeche Victoria Mathias war ein Steinkohlenbergwerk im Essener Nordviertel nahe der Innenstadt. Die Gewerkschaft des Steinkohlenbergwerks Victoria Mathias war eines der Gruendungsmitglieder des Rheinisch-Westfaelischen Kohlen-Syndikats.',
51.4675, 7.013056),
(34,
'Zum Treppchen',
'http://10.0.2.2/img/sure/zumtreppchen.jpg',
'Die Kirche St. Lambertus ist eine katholische Pfarrkirche in Castrop-Rauxel. Sie liegt im Zentrum des Stadtteils Castrop und vor der Kirche kann man sich volllaufen lassen.',
51.548462, 7.310952)
;
